#!/usr/bin/env bash

echo ""
echo "  🌿 hyphae - session continuity across machines"
echo ""
echo "  Translocation of working state through shared substrate."
echo ""
echo "  COMMANDS"
echo "  ────────────────────────────────────────────────────────"
echo ""
echo "  sporulate    Save a single thread of working state."
echo "               Captures: task, decisions, open questions,"
echo "               next steps, relevant files, machine origin."
echo ""
echo "  fruit        Full environment snapshot. Captures all"
echo "               active threads, repo states (branches,"
echo "               dirty files), goose extensions, priorities,"
echo "               and working memory. Auto-runs on sync."
echo ""
echo "  germinate    Resume on another machine. If a fruit"
echo "               exists, presents the full environment with"
echo "               selective hydration (choose which threads"
echo "               and repos to activate). If no fruit, reads"
echo "               the most recent thread."
echo ""
echo "  primordia    List all active threads. What's forming,"
echo "               not yet complete."
echo ""
echo "  senescence   Mark a thread as complete. Graceful closure."
echo "               Moves to history."
echo ""
echo "  SELECTIVE GERMINATION"
echo "  ────────────────────────────────────────────────────────"
echo ""
echo "  When a fruit exists from another machine, germinate"
echo "  presents a menu:"
echo ""
echo "    - All active threads (pick which to hydrate)"
echo "    - Repo states (branch mismatches flagged)"
echo "    - Extension gaps (what's missing on this machine)"
echo "    - Patches available (dirty work from the other side)"
echo "    - Priorities and working memory"
echo ""
echo "  You choose what to activate. Not all-or-nothing."
echo ""
echo "  SYNC INTEGRATION"
echo "  ────────────────────────────────────────────────────────"
echo ""
echo "  When you say \"sync\", hyphae auto-fruits before push:"
echo ""
echo "    sync = fruit -> pull all -> commit all -> push all"
echo ""
echo "  The fruit travels with the push. The other machine"
echo "  pulls and sees fresh state on session start."
echo ""
echo "  USAGE"
echo "  ────────────────────────────────────────────────────────"
echo ""
echo "  These are MCP tools called by the agent. You can also"
echo "  invoke them conversationally:"
echo ""
echo "    \"sporulate\"          Save current thread"
echo "    \"fruit\"              Full environment snapshot"
echo "    \"germinate\"          Pick up where I left off"
echo "    \"what's forming?\"    Show active threads"
echo "    \"close [thread]\"     Mark thread complete"
echo "    \"sync\"               Auto-fruits, then syncs repos"
echo ""
echo "  DATA"
echo "  ────────────────────────────────────────────────────────"
echo ""
echo "  All state lives in .hyphae/ at your repo root:"
echo ""
echo "    .hyphae/"
echo "    ├── active/       Current threads (YAML)"
echo "    ├── history/      Completed threads (YAML)"
echo "    ├── patches/      Dirty-state diffs (when present)"
echo "    └── fruit.yaml    Last full environment snapshot"
echo ""
echo "  Git is the transport. No external services."
echo "  All files are human-readable YAML."
echo ""
echo "  CONFIGURATION"
echo "  ────────────────────────────────────────────────────────"
echo ""
echo "  HYPHAE_REPO_ROOT    Override repo detection"
echo "  HYPHAE_REPOS        Repos captured by fruit (colon-separated, default: repo root)"
echo "  HYPHAE_EXTRA_REPOS  Additional repos (colon-separated)"
echo "  AGENT_MACHINE       Machine identity (work/personal)"
echo "  SPORE_SESSION_ID    Shared session ID with spore"
echo ""
echo "  RELATED"
echo "  ────────────────────────────────────────────────────────"
echo ""
echo "  spore               Biomimetic memory (decay, proximity)"
echo "  rp-why              Collaboration quality measurement"
echo ""
